## <div align = "center">Homework 3</div>
# <div align = "center">US Census Data</div>

**Welcome to Homework 3!** In this homework you will be using techniques you learned in Week 3. The purpose of this homework for you to do data manipulation with ```Pandas``` and to express your observations. 

Feel free to refer back to week 3 tutorial notebook and ask questions on Piazza!

### Grading

There are a total of five questions and each question is worth 3-5 points.

### Import Library

In [1]:
import pandas as pd

### Load dataset

In [28]:
url = 'https://raw.githubusercontent.com/bitprj/DigitalHistory/master/Week3-Introduction-to-Open-Data-Importing-Data-and-Basic-Data-Wrangling/data/acs2017_county_data.csv'
df = pd.read_csv(url)
df

,CountyId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,1001,Alabama,Autauga County,55036,26899,28137,2.7,75.4,18.9,0.3,...,0.6,1.3,2.5,25.8,24112,74.1,20.2,5.6,0.1,5.2
1,1003,Alabama,Baldwin County,203360,99527,103833,4.4,83.1,9.5,0.8,...,0.8,1.1,5.6,27.0,89527,80.7,12.9,6.3,0.1,5.5
2,1005,Alabama,Barbour County,26201,13976,12225,4.2,45.7,47.8,0.2,...,2.2,1.7,1.3,23.4,8878,74.1,19.1,6.5,0.3,12.4
3,1007,Alabama,Bibb County,22580,12251,10329,2.4,74.6,22.0,0.4,...,0.3,1.7,1.5,30.0,8171,76.0,17.4,6.3,0.3,8.2
4,1009,Alabama,Blount County,57667,28490,29177,9.0,87.4,1.5,0.3,...,0.4,0.4,2.1,35.0,21380,83.9,11.9,4.0,0.1,4.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3215,72145,Puerto Rico,Vega Baja Municipio,54754,26269,28485,96.7,3.1,0.1,0.0,...,1.4,0.6,0.9,31.6,14234,76.2,19.3,4.3,0.2,16.8
3216,72147,Puerto Rico,Vieques Municipio,8931,4351,4580,95.7,4.0,0.0,0.0,...,5.0,0.0,1.7,14.9,2927,40.7,40.9,18.4,0.0,12.8
3217,72149,Puerto Rico,Villalba Municipio,23659,11510,12149,99.7,0.2,0.1,0.0,...,2.1,0.0,2.8,28.4,6873,59.2,30.2,10.4,0.2,24.8
3218,72151,Puerto Rico,Yabucoa Municipio,35025,16984,18041,99.9,0.1,0.0,0.0,...,1.4,1.8,0.1,30.5,7878,62.7,30.9,6.3,0.0,25.4
3219,72153,Puerto Rico,Yauco Municipio,37585,18052,19533,99.8,0.2,0.0,0.0,...,1.7,0.1,5.0,24.4,8995,66.4,28.7,5.0,0.0,24.0

## Homework Questions

**Since this dataset has lots of information, feel free to select a set of columns to answer each question.**

In [3]:
df.head()

,CountyId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,1001,Alabama,Autauga County,55036,26899,28137,2.7,75.4,18.9,0.3,...,0.6,1.3,2.5,25.8,24112,74.1,20.2,5.6,0.1,5.2
1,1003,Alabama,Baldwin County,203360,99527,103833,4.4,83.1,9.5,0.8,...,0.8,1.1,5.6,27.0,89527,80.7,12.9,6.3,0.1,5.5
2,1005,Alabama,Barbour County,26201,13976,12225,4.2,45.7,47.8,0.2,...,2.2,1.7,1.3,23.4,8878,74.1,19.1,6.5,0.3,12.4
3,1007,Alabama,Bibb County,22580,12251,10329,2.4,74.6,22.0,0.4,...,0.3,1.7,1.5,30.0,8171,76.0,17.4,6.3,0.3,8.2
4,1009,Alabama,Blount County,57667,28490,29177,9.0,87.4,1.5,0.3,...,0.4,0.4,2.1,35.0,21380,83.9,11.9,4.0,0.1,4.9

### Q1. List out all column names of ```df```.

#### Answer:

In [24]:
df.columns

Index(['CountyId', 'State', 'County', 'TotalPop', 'Men', 'Women', 'Hispanic',
       'White', 'Black', 'Native', 'Asian', 'Pacific', 'VotingAgeCitizen',
       'Income', 'IncomeErr', 'IncomePerCap', 'IncomePerCapErr', 'Poverty',
       'ChildPoverty', 'Professional', 'Service', 'Office', 'Construction',
       'Production', 'Drive', 'Carpool', 'Transit', 'Walk', 'OtherTransp',
       'WorkAtHome', 'MeanCommute', 'Employed', 'PrivateWork', 'PublicWork',
       'SelfEmployed', 'FamilyWork', 'Unemployment'],
      dtype='object')

### Q2. Set ```CountyId``` as an index for ```df```.

In [29]:
df.set_index(keys='CountyId', inplace=True)

In [30]:
df

,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
CountyId,,,,,,,,,,,,,,,,,,,,,
1001,Alabama,Autauga County,55036,26899,28137,2.7,75.4,18.9,0.3,0.9,...,0.6,1.3,2.5,25.8,24112,74.1,20.2,5.6,0.1,5.2
1003,Alabama,Baldwin County,203360,99527,103833,4.4,83.1,9.5,0.8,0.7,...,0.8,1.1,5.6,27.0,89527,80.7,12.9,6.3,0.1,5.5
1005,Alabama,Barbour County,26201,13976,12225,4.2,45.7,47.8,0.2,0.6,...,2.2,1.7,1.3,23.4,8878,74.1,19.1,6.5,0.3,12.4
1007,Alabama,Bibb County,22580,12251,10329,2.4,74.6,22.0,0.4,0.0,...,0.3,1.7,1.5,30.0,8171,76.0,17.4,6.3,0.3,8.2
1009,Alabama,Blount County,57667,28490,29177,9.0,87.4,1.5,0.3,0.1,...,0.4,0.4,2.1,35.0,21380,83.9,11.9,4.0,0.1,4.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72145,Puerto Rico,Vega Baja Municipio,54754,26269,28485,96.7,3.1,0.1,0.0,0.0,...,1.4,0.6,0.9,31.6,14234,76.2,19.3,4.3,0.2,16.8
72147,Puerto Rico,Vieques Municipio,8931,4351,4580,95.7,4.0,0.0,0.0,0.0,...,5.0,0.0,1.7,14.9,2927,40.7,40.9,18.4,0.0,12.8
72149,Puerto Rico,Villalba Municipio,23659,11510,12149,99.7,0.2,0.1,0.0,0.0,...,2.1,0.0,2.8,28.4,6873,59.2,30.2,10.4,0.2,24.8
72151,Puerto Rico,Yabucoa Municipio,35025,16984,18041,99.9,0.1,0.0,0.0,0.0,...,1.4,1.8,0.1,30.5,7878,62.7,30.9,6.3,0.0,25.4
72153,Puerto Rico,Yauco Municipio,37585,18052,19533,99.8,0.2,0.0,0.0,0.0,...,1.7,0.1,5.0,24.4,8995,66.4,28.7,5.0,0.0,24.0

### Q3 (a) Find the rows where ```Unemployment``` is greater than 10.

In [37]:
df.loc[df['Unemployment'] > 10]

,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
CountyId,,,,,,,,,,,,,,,,,,,,,
1005,Alabama,Barbour County,26201,13976,12225,4.2,45.7,47.8,0.2,0.6,...,2.2,1.7,1.3,23.4,8878,74.1,19.1,6.5,0.3,12.4
1011,Alabama,Bullock County,10478,5616,4862,0.3,21.6,75.6,1.0,0.7,...,6.2,1.7,3.0,29.8,4290,81.4,13.6,5.0,0.0,12.1
1015,Alabama,Calhoun County,115527,55593,59934,3.6,72.7,20.4,0.2,1.0,...,1.3,1.1,3.2,24.8,47392,74.9,19.9,5.1,0.1,10.1
1025,Alabama,Clarke County,24625,11649,12976,0.2,53.0,45.7,0.1,0.5,...,0.7,2.7,0.9,23.9,7933,83.1,11.8,5.1,0.0,15.2
1035,Alabama,Conecuh County,12649,6040,6609,1.8,50.3,46.3,0.2,0.0,...,0.8,0.4,1.7,29.6,3945,79.5,12.3,7.2,1.0,14.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72145,Puerto Rico,Vega Baja Municipio,54754,26269,28485,96.7,3.1,0.1,0.0,0.0,...,1.4,0.6,0.9,31.6,14234,76.2,19.3,4.3,0.2,16.8
72147,Puerto Rico,Vieques Municipio,8931,4351,4580,95.7,4.0,0.0,0.0,0.0,...,5.0,0.0,1.7,14.9,2927,40.7,40.9,18.4,0.0,12.8
72149,Puerto Rico,Villalba Municipio,23659,11510,12149,99.7,0.2,0.1,0.0,0.0,...,2.1,0.0,2.8,28.4,6873,59.2,30.2,10.4,0.2,24.8
72151,Puerto Rico,Yabucoa Municipio,35025,16984,18041,99.9,0.1,0.0,0.0,0.0,...,1.4,1.8,0.1,30.5,7878,62.7,30.9,6.3,0.0,25.4
72153,Puerto Rico,Yauco Municipio,37585,18052,19533,99.8,0.2,0.0,0.0,0.0,...,1.7,0.1,5.0,24.4,8995,66.4,28.7,5.0,0.0,24.0

### Q3 (b) How many counties have ```Unemployment``` > 10?

#### Answer:

In [ ]:
# type your answer here
346

### Q4. Find the state with most self-employeed population.

In [40]:
# write your code here
df.groupby(['State'])['SelfEmployed'].sum().sort_values(ascending=False)

State
Texas                   2268.2
Nebraska                1213.6
Kansas                  1075.8
Georgia                  972.5
Missouri                 959.7
South Dakota             918.1
Iowa                     890.7
North Dakota             789.0
Kentucky                 781.6
Tennessee                759.7
Virginia                 740.3
Montana                  738.4
Minnesota                702.6
North Carolina           669.7
Illinois                 667.0
Puerto Rico              652.2
Colorado                 639.0
Oklahoma                 619.6
California               554.9
Arkansas                 553.2
Michigan                 536.6
Wisconsin                511.6
Indiana                  486.2
Ohio                     486.1
Mississippi              475.7
Florida                  422.0
Pennsylvania             402.3
New York                 402.1
Idaho                    386.5
Alabama                  373.4
Louisiana                357.3
Oregon                   332.6
Washington               299.2
West Virginia            267.1
South Carolina           248.8
New Mexico               237.3
Alaska                   209.4
Wyoming                  179.3
Utah                     172.4
Maine                    162.4
Vermont                  138.9
Maryland                 136.0
Nevada                   120.1
Massachusetts            116.8
New Jersey                99.8
Arizona                   89.3
New Hampshire             77.1
Connecticut               50.0
Hawaii                    37.7
Rhode Island              31.1
Delaware                  13.0
District of Columbia       4.3
Name: SelfEmployed, dtype: float64

#### Answer:

In [ ]:
# type your answer here
Texas

### Q5 (a) Select the state with most self-employed population and save the dataframe as ```df_self_emp```.

In [41]:
df_self_emp = df.loc[df['State']=='Texas']

### Q5 (b) Find out top 2 most popular means of transportation to work in ```df_self_emp```.

In [42]:
df_self_emp[['Drive','Carpool','Transit','Walk','OtherTransp','WorkAtHome']].sum()

Drive          20455.0
Carpool         2888.5
Transit           79.4
Walk             600.6
OtherTransp      363.2
WorkAtHome      1013.9
dtype: float64

#### Answer:

In [ ]:
Drive, carpool

### Q6. What are the top 3 states with highest ```mean commute```?

In [43]:
df.groupby(['State'])['MeanCommute'].sum().sort_values(ascending=False)

State
Texas                   5825.3
Georgia                 4119.7
Virginia                3676.2
Kentucky                3048.9
Missouri                2721.9
Tennessee               2519.0
North Carolina          2518.8
Illinois                2402.2
Indiana                 2241.1
Puerto Rico             2207.0
Ohio                    2153.8
Mississippi             2151.6
Iowa                    1936.4
Michigan                1918.0
Minnesota               1860.6
Kansas                  1860.4
Florida                 1768.2
Alabama                 1754.7
Arkansas                1726.0
Pennsylvania            1701.8
Louisiana               1697.7
Nebraska                1681.4
Oklahoma                1678.1
Wisconsin               1608.7
New York                1594.5
West Virginia           1546.6
California              1480.6
Colorado                1386.6
South Carolina          1198.8
South Dakota            1119.8
Montana                  981.5
North Dakota             970.9
Idaho                    947.4
Washington               904.4
Maryland                 734.3
Oregon                   726.5
New Mexico               665.6
New Jersey               641.2
Utah                     582.8
Wyoming                  441.5
Maine                    376.0
Nevada                   369.5
Massachusetts            354.4
Vermont                  339.6
Arizona                  325.5
Alaska                   324.8
New Hampshire            254.0
Connecticut              207.8
Rhode Island             124.0
Hawaii                   104.6
Delaware                  77.3
District of Columbia      30.0
Name: MeanCommute, dtype: float64

#### Answer

In [ ]:
Texas, Georgia, Virginia

### Q7 (a) Select the subset of data where ```State``` is one of the states we found in question 6 and save it as top_three.

In [44]:
top_three = df.loc[df['State'].isin(['Texas','Georgia','Virginia'])]

### Q7 (b) How many counties are there in the top three states? Hint: use one of the aggregate functions.

In [45]:
top_three['County'].count()

# alternatively, top_three.shape[0]

546

### Q7 (c) Find the County with the most ```MeanCommute``` time in ```top_three```.

In [46]:
top_three.sort_values(by='MeanCommute')

,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
CountyId,,,,,,,,,,,,,,,,,,,,,
48263,Texas,Kent County,680,311,369,21.6,77.1,0.7,0.6,0.0,...,15.0,1.7,1.7,7.7,304,51.3,39.5,8.2,1.0,1.6
48023,Texas,Baylor County,3602,1740,1862,10.1,83.8,3.2,0.0,0.0,...,1.6,1.4,0.6,10.6,1434,70.9,17.2,11.9,0.0,2.3
48487,Texas,Wilbarger County,12972,6415,6557,28.6,59.4,8.0,0.7,0.9,...,1.7,1.3,0.8,11.5,6329,67.8,24.9,6.9,0.4,5.8
48205,Texas,Hartley County,5821,3524,2297,26.2,59.6,8.4,0.0,1.4,...,2.3,0.8,4.7,11.9,2049,76.2,13.0,8.8,2.0,1.2
48269,Texas,King County,289,150,139,26.6,73.4,0.0,0.0,0.0,...,3.5,1.2,4.0,12.4,173,72.8,20.2,6.9,0.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51049,Virginia,Cumberland County,9797,4830,4967,0.1,63.1,32.5,0.9,0.0,...,0.0,2.6,4.9,40.7,4810,70.7,20.0,9.4,0.0,7.0
51187,Virginia,Warren County,38991,19445,19546,4.2,87.6,3.6,0.2,1.2,...,1.6,1.0,6.2,40.7,18753,75.6,17.3,6.9,0.2,6.0
51179,Virginia,Stafford County,141159,70984,70175,11.7,63.7,16.4,0.3,3.1,...,0.9,1.0,5.7,40.9,68238,64.5,31.7,3.6,0.1,4.3
48407,Texas,San Jacinto County,27436,13563,13873,12.5,74.9,10.7,0.5,0.0,...,1.1,2.9,2.6,41.3,10221,77.3,15.0,7.6,0.1,6.5
51193,Virginia,Westmoreland County,17596,8646,8950,6.2,63.8,26.6,0.4,0.4,...,1.0,1.2,9.2,41.5,7696,66.4,25.5,7.9,0.2,7.3

#### Answer:

In [ ]:
Westmoreland County

### Q8. Find the top 5 states with highest income level and find out their top professional working field: 'Professional', 'Service', 'Office', 'Construction', or 'Production.'

(hint: use the same approach as Q6 and Q7.)

In [51]:
df.groupby(['State'])['Income'].sum().sort_values(ascending=False)

State
Texas                   12673162
Virginia                 7483915
Georgia                  6879737
Illinois                 5398899
Iowa                     5290172
Kansas                   5252370
Missouri                 5110060
Minnesota                5005110
Kentucky                 4976459
Nebraska                 4829337
Indiana                  4772721
Ohio                     4553314
North Carolina           4455167
Tennessee                4086578
Michigan                 3945033
Wisconsin                3877158
New York                 3615174
Pennsylvania             3569886
Oklahoma                 3558929
California               3540712
Colorado                 3478628
South Dakota             3326977
North Dakota             3169186
Florida                  3158670
Mississippi              3035535
Arkansas                 2926881
Louisiana                2729861
Alabama                  2698184
Montana                  2673818
West Virginia            2293605
Washington               2110386
Idaho                    2031565
South Carolina           1937832
Alaska                   1926338
Oregon                   1746090
Maryland                 1740988
Utah                     1717054
New Jersey               1618003
Puerto Rico              1436210
New Mexico               1359508
Wyoming                  1358500
Massachusetts             994430
Nevada                    966603
Maine                     794893
Vermont                   773538
Arizona                   687250
New Hampshire             649019
Connecticut               595968
Rhode Island              349532
Hawaii                    343315
Delaware                  183884
District of Columbia       77649
Name: Income, dtype: int64

In [52]:
top_five = df.loc[df['State'].isin(['Texas','Virginia','Georgia','Illinois','Iowa'])]
top_five

,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
CountyId,,,,,,,,,,,,,,,,,,,,,
13001,Georgia,Appling County,18471,9090,9381,9.7,69.6,17.9,0.6,0.8,...,2.4,0.6,2.6,22.0,6951,78.8,16.2,4.9,0.2,7.7
13003,Georgia,Atkinson County,8313,4112,4201,24.6,56.6,17.8,0.7,0.0,...,2.2,2.2,1.2,22.9,3289,82.8,11.6,5.6,0.0,8.4
13005,Georgia,Bacon County,11279,5599,5680,8.5,73.6,14.6,0.0,0.9,...,1.3,1.3,2.1,20.4,4345,77.7,16.1,6.2,0.0,3.1
13007,Georgia,Baker County,3251,1547,1704,5.4,52.1,41.3,0.2,0.6,...,1.1,0.6,1.5,27.4,1286,70.1,23.1,6.8,0.0,2.5
13009,Georgia,Baldwin County,45527,22893,22634,2.2,52.9,41.4,0.3,1.5,...,2.5,1.4,1.7,21.7,17647,68.6,27.7,3.7,0.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51800,Virginia,Suffolk city,88057,42594,45463,4.0,49.7,41.2,0.1,1.6,...,1.2,1.1,3.4,28.4,41009,72.0,23.7,4.2,0.2,6.7
51810,Virginia,Virginia Beach city,450057,221350,228707,7.8,62.5,18.4,0.2,6.5,...,2.7,2.1,3.8,23.7,219573,74.3,21.2,4.4,0.2,5.3
51820,Virginia,Waynesboro city,21620,10438,11182,7.2,77.0,12.2,0.8,1.0,...,1.4,2.0,2.3,21.5,9976,78.9,16.9,4.0,0.1,4.4
51830,Virginia,Williamsburg city,14817,6829,7988,7.7,67.9,14.5,0.2,5.8,...,15.0,3.2,6.6,19.6,6235,64.4,33.8,1.9,0.0,7.3
51840,Virginia,Winchester city,27516,13444,14072,16.9,67.0,9.7,0.2,2.0,...,6.7,2.2,6.6,24.8,13358,80.4,12.6,6.7,0.4,4.3

In [53]:
top_five[['Professional', 'Service', 'Office', 'Construction', 'Production']].sum()

Professional    22994.0
Service         13431.9
Office          16506.8
Construction     9718.9
Production      12050.7
dtype: float64

#### What are the top five states with highest income?

In [ ]:
# write your answer here.
Texas, Virginia, Georgia, Illinois, Iowa

#### What is the most popular working field in the top five states?

In [ ]:
# write your answer here.
Professional

### Q9. Find the state with highest male population.

In [35]:
# write your code here
df.groupby(['State'])['Men'].sum().sort_values(ascending=False)

State
California              19366579
Texas                   13616977
Florida                  9914361
New York                 9604111
Illinois                 6312600
Pennsylvania             6260160
Ohio                     5686081
Georgia                  4968887
North Carolina           4895368
Michigan                 4880579
New Jersey               4372321
Virginia                 4113988
Washington               3580888
Arizona                  3385055
Massachusetts            3293426
Indiana                  3258279
Tennessee                3217073
Missouri                 2981332
Maryland                 2906277
Wisconsin                2864115
Minnesota                2731831
Colorado                 2731315
South Carolina           2376759
Alabama                  2350806
Louisiana                2281239
Kentucky                 2179025
Oregon                   1993822
Oklahoma                 1930615
Connecticut              1754046
Puerto Rico              1653997
Iowa                     1548035
Utah                     1506614
Arkansas                 1461651
Nevada                   1450091
Mississippi              1448717
Kansas                   1445980
New Mexico               1032086
Nebraska                  943547
West Virginia             907621
Idaho                     830627
Hawaii                    713981
New Hampshire             659131
Maine                     651040
Montana                   517860
Rhode Island              512581
Delaware                  456876
South Dakota              430587
Alaska                    386319
North Dakota              382121
District of Columbia      319046
Vermont                   308026
Wyoming                   298301
Name: Men, dtype: int64

#### Answer:

In [ ]:
# type your answer here
California

### Q10. Select the state where male population is greater than female population.
(Hint 1: Find the sum of male and female population at a state level.)

(Hint 2: There are 10 states that meet this condition.)

In [48]:
total_pop = df.groupby(['State'])['Men','Women'].sum()

In [50]:
total_pop.loc[total_pop['Men'] > total_pop['Women']]

                  Men    Women
State
Alaska         386319   352246
Colorado      2731315  2705204
Hawaii         713981   707677
Idaho          830627   826748
Montana        517860   512002
Nevada        1450091  1437634
North Dakota   382121   363354
South Dakota   430587   424857
Utah          1506614  1487327
Wyoming        298301   284899

In [ ]:
# type your answer here.
Alaska, Colorado, Hawaii, Idaho, Montana, Nevada, North Dakota, South Dakota, Utah, Wyoming